source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LotameDMP_Example' do
  pod "LotameDMP", :path => "../"
end

target 'LotameDMP_Tests' do
  pod "LotameDMP", :path => "../"
  pod 'OHHTTPStubs'
  
end
